apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: one-pool-vct-resources-volume-2
spec:
  pools:
    - servers: 1
      volumesPerServer: 2
      volumeClaimTemplate:
        metadata:
          name: disk1
        spec:
          resources:
            requests:
              storage: 0
