apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: one-pool-vct-no-request
spec:
  pools:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: disk1

