apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: two-pools-two-volumes-total
spec:
  pools:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: disk1
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: disk1
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
