# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: minio-operator

release:
   name_template: "Version {{.Version}}"
   github:
    owner: minio
    name: operator

before:
  hooks:
    - make clean
    - go generate ./...
    - go mod tidy
    - go mod download

builds:
  -
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    flags:
      - -trimpath
    hooks:
      post: ./minisign.sh {{ .Path }}
  -
    id: kubectl-minio
    dir: kubectl-minio
    binary: kubectl-minio
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    flags:
      - -trimpath
    hooks:
      post: ./minisign.sh {{ .Path }}

archives:
  -
    format: binary
    files:
      - "*.minisig"

dockers:
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    dockerfile: Dockerfile.release
    image_templates:
      - "minio/k8s-operator:{{ .Tag }}"
      - "minio/k8s-operator:latest"
    extra_files:
      - LICENSE
      - README.md
      - CREDITS
      - minio-operator.minisig
      - ca-certificates.crt
