apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: minio
## If specified, MinIOInstance pods will be dispatched by specified scheduler.
## If not specified, the pod will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler
spec:
  zones:
    - name: "zone-0"
      ## Number of MinIO servers/pods in this zone.
      servers: 4
    - name: "zone-1"
      ## Number of MinIO servers/pods in this zone.
      servers: 4
