apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio-operator
  template:
    metadata:
      labels:
        name: minio-operator
    spec:
      serviceAccountName: minio-operator
      containers:
        - name: minio-operator
          image: minio/k8s-operator:v3.0.13
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-access
      volumes:
        - name: docker-access
          hostPath:
            path: /var/run/docker.sock
